#!/usr/bin/env bash
set -euo pipefail

if xrandr --query | grep -q '^HDMI-A-0 connected'; then
  xrandr \
    --output HDMI-A-0 --mode 3840x2160 --rate 30 --rotate left --pos 0x0 \
    --output eDP --primary --mode 1600x2560 --rate 144 --rotate right --below HDMI-A-0 \
    --output DisplayPort-0 --off
else
  xrandr \
    --output eDP --primary --mode 1600x2560 --rate 144 --rotate right
fi
